#JavaSE3
#create at 2021/12/27 22:56 星期一
#by Alyian

server:
  servlet:
    context-path: /
  port: 18981

spring:

  datasource:
    url: jdbc:mysql://101.42.243.87:3306/ssdb?serverTimezone=GMT%2B8&useUnicode=true&useSSL=false&allowMultiQueries=true&characterEncoding=utf8
    username: root
    password: 689929
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 10
      max-active: 20
      initial-size: 10
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true


mybatis-plus:

  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:com/**/Mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    root: info

